return {
	particle_folder = {
	},
	soundfile = {
		"soundevents/game_sounds_creeps.vsndevts",
		"soundevents/game_sounds_items.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_treant.vsndevts",
		"soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts",
	},
	particle = {
		"particles/econ/items/zeus/lightning_weapon_fx/zuus_lightning_bolt_immortal_lightning.vpcf",
		"particles/econ/items/faceless_void/faceless_void_weapon_voidhammer/faceless_void_weapon_voidhammer.vpcf",
		"particles/generic_gameplay/generic_stunned.vpcf",
		"particles/skills/heal_device.vpcf",
		"particles/heroes/omni_knight/thunder_barrier.vpcf",
		"particles/units/heroes/hero_leshrac/leshrac_lightning_slow.vpcf",
		"particles/heroes/revelater/revelater_cash.vpcf",
		"particles/econ/items/templar_assassin/templar_assassin_focal/templar_meld_focal_overhead.vpcf",
		"particles/heroes/revelater/revelater_motion.vpcf",
		"particles/heroes/revelater/revelater_trail_ultimate.vpcf",
		"particles/heroes/drow_ranger/drow_ranger_0_1.vpcf",
		"particles/heroes/drow_ranger/drow_ranger_0_2.vpcf",
		"particles/heroes/oracle/oracle_1_buff.vpcf",
		"particles/units/heroes/hero_oracle/oracle_purifyingflames.vpcf",
		"particles/econ/items/pets/pet_frondillo/pet_flee_frondillo.vpcf",
		"particles/econ/items/pets/pet_generic/pet_flee.vpcf",
		"particles/generic_gameplay/dropped_item.vpcf",
		"particles/skills/green_protect.vpcf",
		"particles/units/heroes/hero_centaur/centaur_warstomp.vpcf",
		"particles/items2_fx/refresher.vpcf",
		"particles/items2_fx/veil_of_discord_debuff.vpcf",
		"particles/items/battlefury_ring/battlefury_ring_eclipse.vpcf",
		"particles/units/heroes/hero_morphling/morphling_base_attack.vpcf",
		"particles/econ/courier/courier_flopjaw/courier_flopjaw_ambient_water.vpcf",
		"particles/units/heroes/hero_viper/viper_base_attack.vpcf",
		"particles/units/heroes/hero_viper/viper_nethertoxin_debuff.vpcf",
		"particles/units/heroes/hero_obsidian_destroyer/obsidian_destroyer_prison_top_orb.vpcf",
	},
	model = {
		"models/props_gameplay/rune_haste01.vmdl",
		"models/props_gameplay/rune_regeneration01.vmdl",
		"models/props_gameplay/rune_arcane.vmdl",
		"models/props_gameplay/aegis.vmdl",
		"models/props_gameplay/morokai_orb_dummy.vmdl",
	},
}