"Shops"
{
    "DefShop"
    {
        "item1" "item_ring_shop"
        "item2" "item_ronghe"
        "item3" "item_athena_heal"
        "item4" "item_athena_guard"
        "item5" "item_athena_momian"
        "item6" "item_athena_wudi"
    }
    "PracticeShop"
    {
        "item1" "item_noitem"
    }
    "BossShop"
    {
        "item1" "item_aura_0"
        "item2" "item_aura_1"
        "item3" "item_aura_2"
        "item4" "item_aura_3"
    }
}