"KeyValue"
{
	"omniknight_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/omniknight/omniknight_0"
		"AbilityTextureName"					"omniknight_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES_STRONG"
		"MaxLevel"								"1"
		"AbilityCooldown"						"2"
		"IgnoreCooldownReduction"				"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE| DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"4"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"str_factor"					"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_radius"				"300"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"active_cooldown"				"6"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown"						"2"
			}
		}
	}
	"omniknight_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/omniknight/omniknight_1"
		"AbilityTextureName"					"omniknight_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES_STRONG"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_ATTACK"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"0"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"str_factor"					"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"400"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"2"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"max_charges"					"3"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"charge_restore_time"			"8"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_charges"				"4"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_increase_pct"			"25"
			}
		}
	}
	"omniknight_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/omniknight/omniknight_2"
		"AbilityTextureName"					"omniknight_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"600"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"60"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_interval"				"1"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_count"					"3"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage"				"10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_jump"					"3"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen"					"10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_regen"					"4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"health_regen_pct"				"0.5 1 1.5 2 2.5 3 3.5 4 4.5 5 5.5 6 6.5 7 7.5 8 8.5 9 9.5 10"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"40"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed_reduce"			"50"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"15"
			}
		}
	}
	"omniknight_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/omniknight/omniknight_3"
		"AbilityTextureName"					"omniknight_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES_STRONG"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attackspeed"				"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_str"						"40 80 120 160 200 240 280 320 360 400 440 480 520 560 600 640 680 720 760 800"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_str_pct"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_chance"					"1"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_str_factor"				"1"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"attack_count"					"8"
			}
		}
	}
	"omniknight_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/omniknight/omniknight_4"
		"AbilityTextureName"					"omniknight_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastPoint"						"0"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"60 120 180 240 300 360 420 480"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_TOGGLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"45 60 75 90 105 120 135 150"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_resistance"				"10 12 14 16 18 20 22 24"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_amp_percent"				"100 125 150 175 200 225 250 275"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_cost"						"10 20 30 40 50 60 70 80"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"palsy_attackspeed"				"80 100 120 140 160 180 200 220"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"palsy_movespeed"				"120 135 150 165 180 195 210 225"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"palsy_duration"				"0.5"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"palsy_interval"				"1"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage"				"10"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"palsy_radius"					"600"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"storm_str_damage"				"10 20 30 40 50 60 70 80"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"storm_jump_count"				"4"
			}
			"13"
			{
				"var_type"						"FIELD_INTEGER"
				"storm_chance"					"30"
			}
			"14"
			{
				"var_type"						"FIELD_FLOAT"
				"storm_interval"				"0.3"
			}
			"15"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attackspeed"				"60 70 80 90 100 110 120 130"
			}
		}
	}
	"templar_assassin_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/templar_assassin/templar_assassin_0"
		"AbilityTextureName"					"templar_assassin_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"PurgeType"								"PurgeTypeStrong"
		"MaxLevel"								"1"
		"AbilityCharges"						"3"
		"AbilityChargeRestoreTime"				"6"
		"AbilityCooldown"						"0"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"charge_restore_time"			"6"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"max_charges"					"3"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"cost_pct_per_stack"			"3"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage"				"10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_radius"				"300"
			}
		}
	}
	"templar_assassin_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/templar_assassin/templar_assassin_1"
		"AbilityTextureName"					"templar_assassin_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_ATTACK"
		"AbilityCastRange"						"800"
		"AbilityCastPoint"						"0.1"
		"AbilityCooldown"						"8"
		"AbilityManaCost"						"40 80 120 160 200 240 280 320 360 400 440 480 520 560 600 640 680 720 760 800"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"250 500 750 1000 1250 1500 1750 2000 2250 2500 2750 3000 3250 3500 3750 4000 4250 4500 4750 5000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"health_pct"					"30"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"angle"							"90"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"600"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"2000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_pct"						"50"
			}
		}
	}
	"templar_assassin_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/templar_assassin/templar_assassin_2"
		"AbilityTextureName"					"templar_assassin_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1600"
		"AbilityCastPoint"						"0.1"
		"AbilityCharges"						"3"
		"AbilityChargeRestoreTime"				"6"
		"AbilityCooldown"						"0"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityManaCost"						"20 40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"1600"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"800"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"50"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"200"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_refresh_chance"		"30"
			}
		}
	}
	"templar_assassin_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/templar_assassin/templar_assassin_3"
		"AbilityTextureName"					"templar_assassin_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_ATTACK"
		"AbilityCooldown"						"8"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityManaCost"						"60 120 180 240 300 360 420 480 540 600 660 720 780 840 900 960 1020 1080 1140 1200"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"resistance"					"5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"150"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_tick"					"0.25"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"active_radius"					"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"active_duration"				"1"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.5"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_range"			"20 40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_stun_duration"			"2"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
		}
	}
	"templar_assassin_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/templar_assassin/templar_assassin_4"
		"AbilityTextureName"					"templar_assassin_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCooldown"						"30"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"200 400 600 800 1000 1200 1400 1600"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_TOGGLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"400 800 1200 1600 2000 2400 2800 3200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_tick"					"0.2"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_cost_pct"					"2"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"turn_rate"						"80"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"100"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"duration"						"0.1"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_chance"				"15"
			}
		}
	}
	"drow_ranger_0_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_0_1"
		"AbilityTextureName"					"drow_ranger_frost_arrows"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_damage"					"5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.5"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"agi_damage_increase"			"0.01"
			}
		}
	}
	"drow_ranger_0_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_0_2"
		"AbilityTextureName"					"drow_ranger_0_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_factor"					"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_range"			"550"
			}
		}
	}
	"drow_ranger_1_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_1_1"
		"AbilityTextureName"					"drow_ranger_1_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"8"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"arrows_per_sec"				"16"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"1000"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"15"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown"						"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"agility_damage"				"1.5"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"30"
			}
			"10"
			{
				"var_type"						"FIELD_FLOAT"
				"reduce_duration"				"1.5"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"collision_radius"				"50"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"900"
			}
		}
	}
	"drow_ranger_1_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_1_2"
		"AbilityTextureName"					"drow_ranger_1_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCooldown"						"12"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"count"							"4"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"attack_factor"					"0.25"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.3"
			}
		}
	}
	"drow_ranger_2_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_2_1"
		"AbilityTextureName"					"drow_ranger_marksmanship"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"10"
		"AbilityManaCost"						"60"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_damage"					"2"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
		}
	}
	"drow_ranger_2_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_2_2"
		"AbilityTextureName"					"drow_ranger_3_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"10"
		"AbilityManaCost"						"60"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_damage"					"2"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
		}
	}
	"drow_ranger_3_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_3_1"
		"AbilityTextureName"					"drow_ranger_marksmanship"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PURE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"agi_damage"					"1.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"-10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_duration"				"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"require_count"					"8"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"curse_duration"				"2"
			}
		}
	}
	"drow_ranger_3_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_3_2"
		"AbilityTextureName"					"drow_ranger_3_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"agi_damage"					"0.1"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"extra_agi_damage"				"4"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"require_count"					"30"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_percent"					"40"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"debuff_duration"				"3"
			}
		}
	}
	"drow_ranger_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_0"
		"AbilityTextureName"					"drow_ranger_frost_arrows"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"AbilityCooldown"						"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_damage"					"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.5"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"agi_damage_increase"			"0.01"
			}
		}
	}
	"drow_ranger_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_1"
		"AbilityTextureName"					"drow_ranger_1_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"8"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"900"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"arrows_per_sec"				"16"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"1000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"15"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"curse_duration"				"2"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"require_count"					"8"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"agility_damage"				"0.25 0.5 0.75 1 1.25 1.5 1.75 2 2.25 2.5 2.75 3 3.25 3.5 3.75 4 4.25 4.5 4.75 5"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"30"
			}
			"12"
			{
				"var_type"						"FIELD_FLOAT"
				"reduce_duration"				"1.5"
			}
			"13"
			{
				"var_type"						"FIELD_INTEGER"
				"collision_radius"				"50"
			}
		}
	}
	"drow_ranger_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_2"
		"AbilityTextureName"					"drow_ranger_1_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCooldown"						"12"
		"AbilityManaCost"						"20 40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"count"							"4"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"attack_factor"					"0.25 0.5 0.75 1 1.25 1.5 1.75 2 2.25 2.5 2.75 3 3.25 3.5 3.75 4 4.25 4.5 4.75 5"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.3"
			}
		}
	}
	"drow_ranger_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_3"
		"AbilityTextureName"					"drow_ranger_3_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"25 50 75 100 125 150 175 200 225 250 275 300 325 350 375 400 425 450 475 500"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"attack_damage"					"0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"extra_agi_damage"				"4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"require_count"					"30"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_percent"					"40"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"debuff_duration"				"3"
			}
		}
	}
	"drow_ranger_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/drow_ranger/drow_ranger_4"
		"AbilityTextureName"					"drow_ranger_marksmanship_ti9"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastPoint"						"2"
		"AbilityCooldown"						"60"
		"AbilityManaCost"						"200 400 600 800 1000 1200 1400 1600"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"broke_damage"					"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"agi_damage"					"120 240 360 480 600 720 840 960"
			}
		}
	}
	"spectre_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_0"
		"AbilityTextureName"					"spectre_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityCooldown"						"3"
		"IgnoreCooldownReduction"				"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityManaCost"						"100"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"unit_limit"					"6"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"attack_count"					"3"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"60"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"health"						"30"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_illusion_damage"		"100"
			}
		}
	}
	"spectre_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_1"
		"AbilityTextureName"					"spectre_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCooldown"						"3"
		"AbilityManaCost"						"100"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"2000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"200"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"per_damage"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"root_duration"					"1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 3.5 3.7 3.9 4.1 4.3 4.5 4.7 4.9 5.1 5.3"
			}
		}
	}
	"spectre_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_2"
		"AbilityTextureName"					"spectre_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCooldown"						"10"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"60"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_limit"					"8 16 24 32 40 48 56 64 72 80 88 96 104 112 120 128 136 144 152 160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"health_cost"					"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_active"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"heal"							"0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3 3.3 3.6 3.9 4.2 4.5 4.8 5.1 5.4 5.7 6"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"450"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"shock_duration"				"3"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_add"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"active_health_cost"			"30"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_min_damage_pct"		"50"
			}
		}
	}
	"spectre_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_3"
		"AbilityTextureName"					"spectre_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"health"						"1"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"max_reduce"					"42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"damage"						"0.05 0.1 0.15 0.2 0.25 0.3 0.35 0.4 0.45 0.5 0.55 0.6 0.65 0.7 0.75 0.8 0.85 0.9 0.95 1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"350"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"regen"							"12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"str"							"0.5 1 1.5 2 2.5 3 3.5 4 4.5 5 5.5 6 6.5 7 7.5 8 8.5 9 9.5 10"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_limit"					"0.1"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"max_radius"					"1200"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"health_str"					"0.3"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"trigge_percent"				"1"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage_limit"			"15"
			}
		}
	}
	"spectre_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_4"
		"AbilityTextureName"					"spectre_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"60"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"300"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"30 60 90 120 150 180 210 240"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"soul_loss"						"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_count"					"4"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"max_bonus_damage"				"30"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"30"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"2.5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"450"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"50"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_time_point"				"1.4"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_cooldown"				"50"
			}
		}
	}
	"spectre_1_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/spectre/spectre_1"
		"AbilityTextureName"					"spectre_1_0"
		"AbilityCastAnimation"					"ACT_DOTA_CAST4_STATUE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_NOT_LEARNABLE | DOTA_ABILITY_BEHAVIOR_HIDDEN"
	}
	"juggernaut_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_0"
		"AbilityTextureName"					"juggernaut_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"1"
		"AbilityCooldown"						"10"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityDuration"						"6"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"critical"						"400"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed"					"100"
			}
		}
	}
	"juggernaut_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_1"
		"AbilityTextureName"					"juggernaut_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"PurgeType"								"PurgeTypeWeak"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_OVERRIDE_ABILITY_1"
		"AbilityCooldown"						"12"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"."								"0.25 0.5 0.75 1 1.25 1.5 1.75 2 2.25 2.5 2.75 3 3.25 3.5 3.75 4 4.25 4.5 4.75 5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"blade_fury_radius"				"600"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed"					"100"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"80"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"blade_fury_damage_tick"		"0.2"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"illusion_damage_percent"		"30"
			}
		}
	}
	"juggernaut_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_2"
		"AbilityTextureName"					"juggernaut_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"PurgeType"								"PurgeTypeWeak"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCooldown"						"30"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilityDuration"						"10"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"output_damage"					"-45 -40 -35 -30 -25 -20 -15 -10 -5 0 5 10 15 20 25 30 35 40 45 50"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"input_damage"					"-1025"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"images_count"					"1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"invuln_duration"				"0.3"
			}
		}
	}
	"juggernaut_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_3"
		"AbilityTextureName"					"juggernaut_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3|4"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilityDuration"						"6"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"damage"						"0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"80 160 240 320 400 480 560 640 720 800 880 960 1040 1120 1200 1280 1360 1440 1520 1600"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_speed"			"15"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"duration"						"4 4.4 4.8 5.2 5.6 6 6.4 6.8 7.2 7.6 8 8.4 8.8 9.2 9.6 10 10.4 10.8 11.2 11.6"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage_pct"			"1"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"scepter_reduce_pct"			"0.5"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_ignore_armor_chance"	"35"
			}
		}
	}
	"juggernaut_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_4"
		"AbilityTextureName"					"juggernaut_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastRange"						"600"
		"AbilityCastPoint"						"0"
		"AbilityCooldown"						"16"
		"AbilityManaCost"						"110"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_NO_INVIS"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilityDuration"						"9"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"duration"						"1.5 1.6 1.7 1.8 1.9 2 2.1 2.2"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.05"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"damage"						"3.6 7.2 10.8 14.4 18 21.6 25.2 28.8"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"4"
			}
		}
	}
	"juggernaut_2_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/juggernaut/juggernaut_2_1"
		"AbilityTextureName"					"juggernaut_2_1"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES_STRONG"
		"MaxLevel"								"20"
		"AbilityCastAnimation"					"ACT_DOTA_ATTACK_EVENT"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"8"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING | DOTA_ABILITY_BEHAVIOR_HIDDEN"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"width"							"225"
			}
		}
	}
	"nevermore_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/nevermore/nevermore_0"
		"AbilityTextureName"					"nevermore_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityCooldown"						"1"
		"IgnoreCooldownReduction"				"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"250"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"5"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"scepter_cooldown"				"0.5"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"trigger_pct"					"90"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"respawn_cooldown"				"30"
			}
		}
	}
	"nevermore_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/nevermore/nevermore_1"
		"AbilityTextureName"					"nevermore_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_RAZE_2"
		"AbilityCastPoint"						"0.55"
		"AbilityCooldown"						"8"
		"AbilityManaCost"						"40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"175 350 525 700 875 1050 1225 1400 1575 1750 1925 2100 2275 2450 2625 2800 2975 3150 3325 3500"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"shadowraze_radius"				"300"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"shadowraze_count"				"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"shadowraze_range"				"300 600 900"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_damage"					"30"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"stack_reduce_damage"			"10"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"max_reduce_damage"				"80"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"8"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"combo_duration"				"3"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_bonus_damage"			"50"
			}
		}
	}
	"nevermore_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/nevermore/nevermore_2"
		"AbilityTextureName"					"nevermore_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_RAZE_3"
		"AbilityCastPoint"						"0.55"
		"AbilityCooldown"						"45"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen_pct"				"4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"20"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"16"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"scepter_interval"				"0.5"
			}
		}
	}
	"nevermore_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/nevermore/nevermore_3"
		"AbilityTextureName"					"nevermore_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_TOGGLE | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"attack_per_str"				"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_cost"						"10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"active_factor"					"2"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attackspeed"				"20 40 60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400"
			}
		}
	}
	"nevermore_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/nevermore/nevermore_4"
		"AbilityTextureName"					"nevermore_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_6"
		"AbilityCastPoint"						"1.67"
		"AbilityCooldown"						"50"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"300 600 900 1200 1500 1800 2100 2400"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"6 12 18 24 30 36"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"soul_count"					"24"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"1200"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"fear_duration"					"3.6"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"line_width_start"				"125"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"line_width_end"				"350"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"line_speed"					"700"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"pull_speed"					"30"
			}
			"10"
			{
				"var_type"						"FIELD_FLOAT"
				"tick_rate"						"0.1"
			}
			"11"
			{
				"var_type"						"FIELD_FLOAT"
				"pull_rotate_speed"				"0.25"
			}
			"12"
			{
				"var_type"						"FIELD_FLOAT"
				"animation_rate"				"0.2"
			}
		}
	}
	"rubick_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/rubick/rubick_0"
		"AbilityTextureName"					"rubick_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"center_damage"					"5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"center_radius"					"50"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"max_count"						"5"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_factor"					"5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bounce_radius"					"500"
			}
		}
	}
	"rubick_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/rubick/rubick_1"
		"AbilityTextureName"					"rubick_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"1400"
		"AbilityCooldown"						"13"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"pull_damage"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"pull_duration"					"0.6"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"pull_bonus"					"2"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"open_damage"					"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.1"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.5"
			}
		}
	}
	"rubick_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/rubick/rubick_2"
		"AbilityTextureName"					"rubick_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_5"
		"AbilityCastRange"						"3000"
		"AbilityCharges"						"3"
		"AbilityChargeRestoreTime"				"8"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"80 95 110 125 140 155 170 185 200 215 230 245 260 275 290 305 320 335 350 365"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"delay"							"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"shield_factor"					"50"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"shield_duration"				"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_delay"					"0"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_factor"				"2"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown_reduction"			"15"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"1"
			}
		}
	}
	"rubick_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/rubick/rubick_3"
		"AbilityTextureName"					"rubick_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1400"
		"AbilityCooldown"						"18"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityManaCost"						"160 190 220 250 280 310 340 370 400 430 460 490 520 550 580 610 640 670 700 730"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"delay"							"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"400"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_delay"					"0"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"scepter_interval"				"0.25"
			}
		}
	}
	"rubick_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/rubick/rubick_4"
		"AbilityTextureName"					"rubick_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"SpellDispellableType"					"SPELL_DISPELLABLE_NO"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastRange"						"1000"
		"AbilityCooldown"						"40"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"300 450 600 750 900 1050 1200 1350"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1 2 3 4 5 6 7 8"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"100"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed"					"99999"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"1"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"interval_reduction"			"0.925"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"count"							"50"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"10"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_count"					"80"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"health_reduce_pct"				"20"
			}
		}
	}
	"windrunner_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/windrunner/windrunner_0"
		"AbilityTextureName"					"windrunner_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"1"
		"AbilityCastRange"						"800"
		"AbilityCharges"						"3"
		"AbilityChargeRestoreTime"				"16"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityManaCost"						"100"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_range"			"250"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attackspeed"				"400"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"attacktime"					"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"8"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"delay_pct"						"20"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage"				"10"
			}
		}
	}
	"windrunner_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/windrunner/windrunner_1"
		"AbilityTextureName"					"windrunner_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1500"
		"AbilityCooldown"						"9"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityChannelTime"					"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_CHANNELLED | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"30 60 90 120 150 180 210 240 270 300 330 360 390 420 450 480 510 540 570 600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"range"							"1200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"3000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"125"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.4"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown_reduction"			"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_range"					"800"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage_pct"				"60"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_chance"				"15"
			}
		}
	}
	"windrunner_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/windrunner/windrunner_2"
		"AbilityTextureName"					"windrunner_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCooldown"						"20"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"spirit_count"					"3"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"12"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"1"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"1200"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"width"							"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"armor_reduce"					"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_duration"				"4"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"speed"							"1200"
			}
		}
	}
	"windrunner_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/windrunner/windrunner_3"
		"AbilityTextureName"					"windrunner_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"SpellDispellableType"					"SPELL_DISPELLABLE_YES"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCharges"						"2"
		"AbilityChargeRestoreTime"				"12"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IMMEDIATE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"54 58 62 66 70 74 78 82 86 90 94 98 102 106 110 114 118 122 126 130"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_pct"					"22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce_pct"			"12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"325"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
		}
	}
	"windrunner_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/windrunner/windrunner_4"
		"AbilityTextureName"					"windrunner_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"90"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2|3"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"5 10 15 20 25 30 35 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_radius"					"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"1200"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.5"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.03"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"chance"						"40"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_bonus_duration"		"4"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_interval"				"8"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_duration"				"1"
			}
		}
	}
	"crystal_maiden_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/crystal_maiden/crystal_maiden_0"
		"AbilityTextureName"					"crystal_maiden_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"15"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1|3"
		"AbilityManaCost"						"50"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_BOTH"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"275"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce_pct"			"8"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"cold_radius"					"900"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"mark_duration"					"10"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"max_count"						"5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_freeze_duration"		"2"
			}
		}
	}
	"crystal_maiden_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/crystal_maiden/crystal_maiden_1"
		"AbilityTextureName"					"crystal_maiden_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastPoint"						"0.3"
		"AbilityCharges"						"3"
		"AbilityChargeRestoreTime"				"15"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"frozen_duration"				"1.2"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed"					"25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius_per_cold"				"100"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_per_cold"				"30"
			}
			"10"
			{
				"var_type"						"FIELD_FLOAT"
				"frozen_per_cold"				"0.3"
			}
		}
	}
	"crystal_maiden_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/crystal_maiden/crystal_maiden_2"
		"AbilityTextureName"					"crystal_maiden_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"800"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"10"
		"AbilityManaCost"						"80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_reduce"				"50"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"slow_duration"					"3"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.8"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"0.4"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"interval_per_cold"				"0.05"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"radius_per_cold"				"30"
			}
		}
	}
	"crystal_maiden_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/crystal_maiden/crystal_maiden_3"
		"AbilityTextureName"					"crystal_maiden_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown_reduce"				"11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_regen"					"8 16 24 32 40 48 56 64 72 80 88 96 104 112 120 128 136 144 152 160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"refresh_chance"				"15"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_max_count"				"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"chance_per_cold"				"1"
			}
		}
	}
	"crystal_maiden_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/crystal_maiden/crystal_maiden_4"
		"AbilityTextureName"					"crystal_maiden_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"30"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"8"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"curse_duration"				"4"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"40 60 80 100 120 140 160 180"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"frozen_speed"					"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"duration_per_cold"				"1"
			}
		}
	}
	"oracle_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/oracle/oracle_0"
		"AbilityTextureName"					"oracle_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.15"
		"AbilityCooldown"						"30"
		"IgnoreCooldownReduction"				"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1"
		"AbilityManaCost"						"50"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_BOTH"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"intellect_stack"				"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"exp_gain_pct"					"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"50"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage_stack"			"1"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"15"
			}
		}
	}
	"oracle_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/oracle/oracle_1"
		"AbilityTextureName"					"oracle_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.15"
		"AbilityCooldown"						"2.25"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_OUT_OF_WORLD"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"80 160 240 320 400 480 560 640 720 800 880 960 1040 1120 1200 1280 1360 1440 1520 1600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_dot"					"0.5 1 1.5 2 2.5 3 3.5 4 4.5 5 5.5 6 6.5 7 7.5 8 8.5 9 9.5 10"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"9"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_reduce_pct"				"30"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_interval"				"1"
			}
		}
	}
	"oracle_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/oracle/oracle_2"
		"AbilityTextureName"					"oracle_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"16"
		"IgnoreCooldownReduction"				"1"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_intellect"				"10 20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"base_level"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"util_level"					"1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown_reduction"			"21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"9"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_bonus_int_pct"			"15"
			}
		}
	}
	"oracle_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/oracle/oracle_3"
		"AbilityTextureName"					"oracle_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastRange"						"1200"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"28"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"3"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"50 100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950 1000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"block_count"					"6 6 6 6 7 7 7 7 8 8 8 8 9 9 9 9 10 10 10 10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"block_duration"				"1"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"14"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_root_radius"			"300"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_root_duration"			"1"
			}
		}
	}
	"oracle_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/oracle/oracle_4"
		"AbilityTextureName"					"oracle_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastRange"						"800"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"60"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"SpellImmunityType"						"SPELL_IMMUNITY_ENEMIES_YES"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"80 160 240 320 400 480 560 640"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"pull_duration"					"0.5"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"2"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"imprison_duration"				"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"200"
			}
		}
	}
	"void_spirit_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/void_spirit/void_spirit_0"
		"AbilityTextureName"					"void_spirit_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"5"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"2"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_cooldown"				"2"
			}
		}
	}
	"void_spirit_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/void_spirit/void_spirit_1"
		"AbilityTextureName"					"void_spirit_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_4"
		"AbilityCastPoint"						"0"
		"AbilityCooldown"						"10"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"1|3"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"base_shield"					"2000 4000 6000 8000 10000 12000 14000 16000 18000 20000 22000 24000 26000 28000 30000 32000 34000 36000 38000 40000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_reduce_pct"				"20"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"shield_per_attack"				"40"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"active_duration"				"0.3"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"debuff_duration"				"6"
			}
		}
	}
	"void_spirit_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/void_spirit/void_spirit_2"
		"AbilityTextureName"					"void_spirit_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastRange"						"1600"
		"AbilityCastPoint"						"0.2"
		"AbilityCharges"						"2"
		"AbilityChargeRestoreTime"				"12"
		"AbilityManaCost"						"60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"275"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"disappear_time"				"1.3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"2"
			}
		}
	}
	"void_spirit_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/void_spirit/void_spirit_3"
		"AbilityTextureName"					"void_spirit_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastPoint"						"0.2"
		"AbilityCharges"						"2"
		"AbilityChargeRestoreTime"				"8"
		"HasScepterUpgrade"						"1"
		"ScepterLevel"							"4"
		"AbilityManaCost"						"20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_IGNORE_BACKSWING"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"175"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"min_travel_distance"			"200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"max_travel_distance"			"1600"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"pop_damage_delay"				"1.25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"movement_slow_pct"				"80"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"search_radius"					"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"400 800 1200 1600 2000 2400 2800 3200 3600 4000 4400 4800 5200 5600 6000 6400 6800 7200 7600 8000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"10"
			}
		}
	}
	"void_spirit_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/void_spirit/void_spirit_4"
		"AbilityTextureName"					"void_spirit_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_3"
		"AbilityCastPoint"						"0.2"
		"AbilityCooldown"						"40"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitTargetFlags"				"DOTA_UNIT_TARGET_FLAG_MAGIC_IMMUNE_ENEMIES"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"400 800 1200 1600 2000 2400 2800 3200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"100 200 300 400 500 600 700 800"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"275"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"disappear_time"				"1.3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"portals_per_ring"				"6"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"destination_fx_radius"			"183"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"angle_per_ring_portal"			"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"first_ring_distance_offset"	"520"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"6"
			}
		}
	}
	"monkey_king_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/monkey_king/monkey_king_0"
		"AbilityTextureName"					"monkey_king_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PURE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_reduce"					"0.5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deep"					"2"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_chance"				"15"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_critical"				"50"
			}
		}
	}
	"monkey_king_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/monkey_king/monkey_king_1"
		"AbilityTextureName"					"monkey_king_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_MK_STRIKE"
		"AbilityCooldown"						"10"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"strike_damage"					"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"350"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"1200"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"4"
			}
		}
	}
	"monkey_king_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/monkey_king/monkey_king_2"
		"AbilityTextureName"					"monkey_king_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCooldown"						"16"
		"AbilityManaCost"						"80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250 260 270"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_reduce_percent"			"2.5 5 7.5 10 12.5 15 17.5 20 22.5 25 27.5 30 32.5 35 37.5 40 42.5 45 47.5 50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_armor"					"10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"2"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"shield_duration"				"10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"cooldown_reduce"				"80"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"120"
			}
		}
	}
	"monkey_king_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/monkey_king/monkey_king_3"
		"AbilityTextureName"					"monkey_king_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCooldown"						"20"
		"AbilityManaCost"						"40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"cleave_radius"					"300"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"cleave_damage"					"60 80 100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440"
			}
			"03"
			{
				"var_type"						"FIELD_FLOAT"
				"duration"						"6.5 7 7.5 8 8.5 9 9.5 10 10.5 11 11.5 12 12.5 13 13.5 14 14.5 15 15.5 16"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"summon_count"					"2"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"max_count"						"9"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_interval"				"4"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_duration"				"12"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_counter_duration"		"2"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_counter_attack"		"1"
			}
		}
	}
	"monkey_king_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/monkey_king/monkey_king_4"
		"AbilityTextureName"					"monkey_king_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_MK_STRIKE"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"60"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_PHYSICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"thump_damage"					"40 80 120 160 200 240 280 320"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"thump_radius"					"1200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"thump_duration"				"1"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"crush_damage"					"80 160 240 320 400 480 560 640"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"crush_radius"					"400"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"crush_duration"				"4"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"pure_pct"						"20 30 40 50 60 70 80 90"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_count"					"9"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"scepter_damage"				"20"
			}
		}
	}
	"lina_0"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/lina/lina_0"
		"AbilityTextureName"					"lina_0"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"1"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"1"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"reduce"						"0.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"350"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"1"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"ignite_count"					"1"
			}
		}
	}
	"lina_1"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/lina/lina_1"
		"AbilityTextureName"					"lina_1"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"2000"
		"AbilityCastPoint"						"0.48"
		"AbilityCooldown"						"12"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"200 400 600 800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800 3000 3200 3400 3600 3800 4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"distance"						"2000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"width"							"200"
			}
			"06"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.5"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"100"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"miss_duration"					"3.5"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"ignite_count"					"6"
			}
		}
	}
	"lina_2"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/lina/lina_2"
		"AbilityTextureName"					"lina_2"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_1"
		"AbilityCastRange"						"1300"
		"AbilityCastPoint"						"0.48"
		"AbilityCooldown"						"6"
		"AbilityManaCost"						"120 140 160 180 200 220 240 260 280 300 320 340 360 380 400 420 440 460 480 500"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"350"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"base_damage"					"80 160 240 320 400 480 560 640 720 800 880 960 1040 1120 1200 1280 1360 1440 1520 1600"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"tick_damage"					"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"1"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"80"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"ignite_count"					"3"
			}
		}
	}
	"lina_3"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/lina/lina_3"
		"AbilityTextureName"					"lina_3"
		"AbilityType"							"DOTA_ABILITY_TYPE_BASIC"
		"MaxLevel"								"20"
		"RequiredLevel"							"1"
		"LevelsBetweenUpgrades"					"3"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"damage"						"0.25 0.5 0.75 1.0 1.25 1.5 1.75 2 2.25 2.5 2.75 3.0 3.25 3.5 3.75 4.0 4.25 4.5 4.75 5.0"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_speed"			"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"1"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"ignite_count"					"1"
			}
		}
	}
	"lina_4"
	{
		"BaseClass"								"ability_lua"
		"ScriptFile"							"abilities/heroes/lina/lina_4"
		"AbilityTextureName"					"lina_4"
		"AbilityType"							"DOTA_ABILITY_TYPE_ULTIMATE"
		"MaxLevel"								"8"
		"RequiredLevel"							"8"
		"LevelsBetweenUpgrades"					"24"
		"AbilityCastAnimation"					"ACT_DOTA_CAST_ABILITY_2"
		"AbilityCastPoint"						"0.3"
		"AbilityCooldown"						"30"
		"AbilityManaCost"						"200 300 400 500 600 700 800 900"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"12 24 36 48 60 72 84 96"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"250"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"max_radius"					"800"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.25 1.5 1.75 2 2.25 2.5 2.75 3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"delay"							"1"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"wave_count"					"12"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"count_per_wave"				"2"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.25"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"ignite_count"					"2"
			}
		}
	}
}
